### ISSUE TITLE
San Mateo is no longer loading

### ISSUE THREAD

**Issue by diamondk** [xke/coronavirus-sf#1]
Please fix if possible!

**Comment by xke** [comment]
Hi @diamondk , Thanks for your alert!
Are you referring to the graphs at https://coronavirus-sf.now.sh/san-mateo-ca.html not appearing -- or that the most recent San Mateo data (at the time of this writing) is from April 6?

**Comment by xke** [comment]
So for the issue with more recent data: The San Mateo public health page I was referencing at https://www.smchealth.org/post/san-mateo-county-covid-19-data-0 currently only has cases as of April 6. I've let San Mateo County know of this issue, so hopefully they can update it soon. Meanwhile, from news reports, I was able to update https://coronavirus-sf.now.sh/san-mateo-ca.html with counts until April 8.

**Comment by diamondk** [comment]
Oh I see.  I think they moved the page.
https://www.smchealth.org/post/san-mateo-county-covid-19-data-1

**Comment by xke** [comment]
Ah ok! Good find @diamondk ! I updated my links to this new page!

**Comment by diamondk** [comment]
ty!

**Comment by xke** [comment]
Thanks again for bringing this to my attention! 👍
